SUPABASE_URL = "https://tfdnrxppkkgzjoopwyyy.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmZG5yeHBwa2tnempvb3B3eXl5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc5MzY3MCwiZXhwIjoyMDcxMzY5NjcwfQ.RP1t4f7KKaCdr_eJfD8JvcIHNSfYgR6aR-ft2bU2gBE"
